### ISSUE TITLE
Need help: determining path to the dll that's built by a dependency

### ISSUE THREAD

**Issue by MOZGIII** [volks73/cargo-wix#76] opened 2019-04-25 18:31 UTC
I have a project that uses [`iui`](https://crates.io/crates/iui) crate, and it produced a `dll` (in particular - `libui.dll`) that I'd like to include with the installer.
This `dll` is provided by `libui-sys` crate. The problem is when it's build, the resulting artifact is stored under a seemingly-random path at the `target` dir, for example: `target/release/build/ui-sys-4e1a9d7334d7f5dd/out/build/out/Release/libui.dll`. The seemingly-random part is `ui-sys-4e1a9d7334d7f5dd`, where `4e1a9d7334d7f5dd` is some number that I can't guess currently. Furthermore, with every build there are two `target/release/build/ui-sys-xxxxxxxxxxxxxxxxxxx` dirs, and ony one of them contains the `dll`. Though, the `xxxxxxxxxxxxxxxxxxx` part seems to be not truly random - it it stable, in a sense that it remains the same across at least same version build. I noticed quite odd behavior in the CI: https://ci.appveyor.com/project/MOZGIII/rebootinto/builds/24093596 - where different rust versions generate the different paths.

So, basicly I'm here to ask if there's a way I can reliably reference this file from the installer?
All I can think of is to try solving this via a cusom build script that would seatch for the lib and copy it to the correct location, but it just feels too much unidiomatic.
Can anyone think of a better way of incuding the `dll` from a dependency in the installer?

**Comment by volks73** [comment] 2019-04-26 14:01
>All I can think of is to try solving this via a cusom build script that would seatch for the lib and copy it to the correct location, but it just feels too much unidiomatic.

By a "custom build script", do you mean a `build.rs` file and the `build` key for Cargo? As mentioned in the [Build Scripts](https://doc.rust-lang.org/cargo/reference/build-scripts.html) documentation, this is useful for "Build a bundled C library" and "Finding a C library on the host system".

You might have to abandoned the DLL that is built for the dependency crate and instead build it yourself as part of your project's build script. This should place the DLL in a reproducible and predictable location, or at the very least, have the location for the DLL available to the rest of your build, and ultimately the installer build, through Cargo, some environment variable, command line option, or a temporary file.

This means you will be building the DLL twice, once for the `libui-sys` crate and second for your crate, but there might be a way to tell the `libui-sys` crate to use your project's DLL through the build script (build.rs) instead of its own, which would avoid a double build. A positive is that the `libui-sys` crate is already successfully building the DLL, so you can use that project as a model for setting up the DLL build in the build script.

**Comment by MOZGIII** [comment] 2019-04-26 15:47
That's an option, but don't really want to take over the control of how the `iui` is implemented - and I feel like the `dll` is a part of the implementation internals they're supposed to provide and I'm supposed to just consume.
Maybe it's the problem of the `libui-sys` crate and I should go there for an advice, or it's a problem of the cargo itself - I'd expect it to provide some assistance for grabbind the build artifacts from the dependencies.

**Comment by crlf0710** [comment] 2019-08-19 05:14
Hello, i'm seeking to make an installer too, and in my case the dlls are build and provided by `vcpkg`. Is there a script that either procedural or declarative that can allow me to specify where to retrieve these files are and where to install them to and package them into the installer?

**Comment by volks73** [comment] 2019-08-19 15:47
@crlf0710 Just to confirm because I am a little confused by your question: you have a Rust project that uses some DLLs that are obtained using vcpkg and you want to include these DLLs in the same installer as your Rust executable/library or you want a separate installer for the DLLs?

If the former, then after generating the WiX Source (WXS) file using the `cargo wix init` command, you can open the `main.wxs` file in a text editor and manually add the DLLs to the installer. This is assuming the DLLs are only really built once and stored in your Rust project somewhere. If you want to build the DLLs when you build the Rust executable/library, then you need to look at using a [build.rs]() file. If the latter of the above question is true, then this is a little outside the scope of this project, but I can possibly given some direction on writing a WXS file.

It might be helpful if you could answer the following questions:

1. Where are the DLLs located in your Rust project relative to the manifest file (Cargo.toml)?
2. Where do you want the DLLs installed when installing the Rust project, i.e. `C:\Program Files\Your-Rust-Project\libs` or something?d

**Comment by crlf0710** [comment] 2019-08-19 17:34
@volks73
Thank you for your help! I haven't put my hands on it yet, just planning. But it's a real and often seen scenario, and i figure this use case would be nice to be covered by cargo-wix.
Let me answer your questions. Suppose I installed `fontconfig` from `vcpkg`, and i used this c library in my rust program, and i want to use `cargo-wix` to package my application. I don't want to always do this packaging on my own machine, i want to write the proper scripts and let the CI do it. So i can't hard code any paths below:
1. The dlls is `M:\Apps\vcpkg\installed\x64-windows\bin\fontconfig.dll` in my machine, The environment variable `VCPKG_ROOT` is `M:\Apps\vcpkg` and this is where the vcpkg itself is installed.
If i'm building 32-bit program, the `x64-windows` part will be `x86-windows` instead, and this is `VCPKG_DEFAULT_TRIPLET` environment variable, on my machine it is `x64-windows`
2. I want to install this dll just beside my executable. So the executable can find it when it's run.

**Comment by volks73** [comment] 2019-08-19 19:56
My initial thought to make the building of an installer portable would be to create a [Build Script](https://doc.rust-lang.org/cargo/reference/build-scripts.html) that reads in the path from the `VCPKG_ROOT` environment variable and copies the various DLLs to the `wix`, or even better `target\wix`, folder of the Rust project on each build from the `VCPKG_ROOT` path. I would make sure the DLLs are ignored by version control if you decide to put them in the `wix` folder instead of the `target\wix` folder. 

This will put the DLLs in a known location relative to the project's manifest file, `Cargo.toml`, and the WXS file, `main.wxs`. With a path relative to the Rust project instead of an absolute path, which is machine dependent, the DLLs can be easily included in the installer. Here is a snippet of adding the DLLs to the installder for the WXS file:

```xml
<!-- ... --->
<Directory Id='TARGETDIR' Name='SourceDir'>
    <Directory Id='$(var.PlatformProgramFilesFolder)' Name='PFiles'>
        <Directory Id='APPLICATIONFOLDER' Name='project-name'>
            <!-- In the most basic form, you can place the DLLs in the same
                 folder as the EXE; otherwise, put them in another folder. I just don't know the
                 DLL loading process for Rust EXEs. The DLLs may need to be in the same folder. -->
            <Directory Id='Bin' Name='bin'>
                <!-- ... --->
                <!-- Repeat the next <component> block for each DLL making sure
                     the `Source` attribute is the path to the DLL. -->
                <Component Id='fontConfig' Guid='*' Win64='$(var.Win64)'>
                    <File
                        Id='fontConfigDll'
                        Name='fontconfig.dll'
                        DiskId='1'
                        Source='target\wix\fontconfig.dll'
                        KeyPath='yes'/>
                </Component>
                <!-- ... --->
            </Directory>
        </Directory>
    </Directory>
</Directory>
<!-- ... --->
```

I am not sure there is a way to do this without having to copy the DLLs in the current implementation of cargo-wix.

**Comment by volks73** [comment] 2019-09-07 19:57
I think this question has ultimately been answered, so I am going to close it.

**Closed by volks73** 2019-09-07 19:57 UTC
Labels: question
