### ISSUE TITLE
Build with debug binaries

### ISSUE THREAD

**Issue by Coding-Badly** [volks73/cargo-wix#93] opened 2020-01-31 17:58 UTC
We're about to start an early view of our product.  We have a need to use the `debug` versions of our binaries in the installation.  Ideally that would include passing "is debug" to WiX so the labeling can match.

**Comment by volks73** [comment] 2020-01-31 23:30
Thank you for the feature request. I think this is a duplicate of #91. By build profiles, I mean [Debug and Release release profiles for cargo](https://doc.rust-lang.org/book/ch14-01-release-profiles.html). I should update #91 to follow the "release profile" naming and description instead of "build profiles".

**Comment by Coding-Badly** [comment] 2020-02-01 00:05
@volks73, I assumed we would be using `debug` versions for our early view.  That is not correct.  We're using `release` versions.  Please don't exert any effort on my behalf.

In any case, thank you for your time, considering my request, and this awesome add-in!

**Comment by volks73** [comment] 2020-02-02 20:52
@Coding-Badly, no worries. I am going to close this issue and use #91 for tracking of the feature.

Just for background, I originally hard-coded the release profile because by the installer would only be used for distribution of end-user releases and developers would not want debugging code available to end-users.

**Closed by volks73** 2020-02-02 20:52 UTC
Labels: duplicate, enhancement
