### ISSUE TITLE
Document usable fields

### ISSUE THREAD

**Issue by fschutt** [volks73/cargo-wix#50] opened 2018-05-17 01:48 UTC
If you support a seperate `[wix]` section - what keys / values are valid? For example, it would be nice, not to add the `main.wxs` into source control. It would be great if settings (app icon, banner, help / documentation link, etc.) could be set via the `Cargo.toml` file instead of the `main.wxs` file:

Also, it would be great, if you could support a "nice name". Cargo will complain if you capitalize the package name (which is OK), but for a user it's often more friendly to have a capitalized name

I.e. something like this:

```toml
[package]
name = "something"

[package.metadata.wix]
nice-name = "Something Editor Pro"
icon = "assets/main.ico"
help = "http://company.com/support"
install-banner-picture = "assets/Banner.bmp"
install-dialog-picture = "assets/Dialog.bmp"
```

It would be great if this could be done directly in the `Cargo.toml` file, so that the `main.wxs` file doesn't need to be checked into version control. If something like this is already possible, it would be good to have some documentation on which fields / keys are valid.

**Comment by volks73** [comment] 2018-05-17 16:34
This is most likely a duplicate of #20. The sub-command currently (v0.0.5) does not support a sub-command specific manifest file or Cargo.toml section, but I like all of these ideas and suggests. Please continue this discussion in #20.

Additionally,

>Also, it would be great, if you could support a "nice name". Cargo will complain if you capitalize the package name (which is OK), but for a user it's often more friendly to have a capitalized name

This is currently possible with the `-p,--product-name` command line option. Use the `cargo wix --help` command for more information and the [documentation](https://volks73.github.io/cargo-wix/cargo_wix/index.html#concepts) also provides some additional information about changing the product name:

>The cargo wix subcommand use the package name for the product name. The default install location is at C:\Program Files\[Product Name], where [Product Name] is replaced with the product name determined from the package name. This can be overridden with the -p,--product-name option. The binary name, which is the name field for the [[bin]] section, is used for the executable file name, i.e. "name.exe". This can also be overridden using the -b,--bin-name option. The package description is used in multiple places for the installer, including the text that appears in the blue UAC dialog when using a signed installer. This can be overridden using the -d,--description option.

If and when a manifest-based configuration system is implemented, a `product-name` field will be absolutely be included.

**Closed by volks73** 2018-05-17 16:34 UTC
