### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by justinmoon** [volks73/cargo-wix#105] opened 2020-07-23 23:09 UTC
Trying to follow [this example](https://volks73.github.io/cargo-wix/cargo_wix/index.html#examples).

```
> cargo init --bin --vcs none --name example
...
> cargo wix init
...
> dir /B
Cargo.toml
src
wix
> cargo wix
DEBUG: self.bin_path = None
DEBUG: self.capture_output = false
DEBUG: self.compiler_args = None
DEBUG: self.culture = Some("en-US")
DEBUG: self.debug_build = false
DEBUG: self.debug_name = false
DEBUG: self.includes = None
DEBUG: self.input = None
DEBUG: self.linker_args = None
DEBUG: self.locale = None
DEBUG: self.name = None
DEBUG: self.no_build = false
DEBUG: self.output = None
DEBUG: self.version = None
DEBUG: manifest_path = "C:\\Users\\justin\\dev\\wix\\example\\Cargo.toml"
DEBUG: cargo_file_path = "C:\\Users\\justin\\dev\\wix\\example\\Cargo.toml"
DEBUG: name = "example"
DEBUG: version = Version { major: 0, minor: 1, patch: 0, pre: [], build: [] }
DEBUG: compiler_args = None
DEBUG: culture = EnUs
DEBUG: linker_args = None
DEBUG: locale = None
DEBUG: platform = X64
DEBUG: debug_build = false
DEBUG: debug_name = false
TRACE: Using the current working directory (CWD) to obtain all WXS files
DEBUG: wxs_sources = ["wix\\main.wxs"]
TRACE: Using the current working directory (CWD) to build the WiX object files destination
DEBUG: wixobj_destination = "target\\wix\\"
DEBUG: no_build = false
 INFO: Building the release binary
DEBUG: builder = "cargo"
DEBUG: command = "cargo" "build" "--release" "--manifest-path" "C:\\Users\\justin\\dev\\wix\\example\\Cargo.toml"
   Compiling example v0.1.0 (C:\Users\justin\dev\wix\example)
    Finished release [optimized] target(s) in 0.59s
 INFO: Compiling the installer
TRACE: Using the 'C:\Program Files (x86)\WiX Toolset v3.11\' path to the WiX Toolset's 'bin' folder for the compiler
DEBUG: compiler = "C:\\Program Files (x86)\\WiX Toolset v3.11\\bin\\candle.exe"
DEBUG: command = "C:\\Program Files (x86)\\WiX Toolset v3.11\\bin\\candle.exe" "-dProfile=release" "-dVersion=0.1.0" "-dPlatform=x64" "-ext" "WixUtilExtension" "-o" "target\\wix\\" "wix\\main.wxs"
Windows Installer XML Toolset Compiler version 3.11.2.4516
Copyright (c) .NET Foundation and contributors. All rights reserved.

main.wxs
DEBUG: wixobj_sources = ["target\\wix\\main.wixobj"]
DEBUG: installer_kind = Msi
TRACE: Using the current working directory (CWD) to build the WiX object files destination
DEBUG: installer_destination = "target\\wix\\example-0.1.0-x86_64.msi"
 INFO: Linking the installer
TRACE: Using the 'C:\Program Files (x86)\WiX Toolset v3.11\' path to the WiX Toolset's 'bin' folder for the linker
DEBUG: linker = "C:\\Program Files (x86)\\WiX Toolset v3.11\\bin\\light.exe"
DEBUG: base_path = "C:\\Users\\justin\\dev\\wix\\example"
DEBUG: command = "C:\\Program Files (x86)\\WiX Toolset v3.11\\bin\\light.exe" "-spdb" "-ext" "WixUIExtension" "-ext" "WixUtilExtension" "-cultures:en-US" "-out" "target\\wix\\example-0.1.0-x86_64.msi" "-b" "C:\\Users\\justin\\dev\\wix\\example" "target\\wix\\main.wixobj"
Windows Installer XML Toolset Linker version 3.11.2.4516
Copyright (c) .NET Foundation and contributors. All rights reserved.

light.exe : error LGHT0001 : The system cannot find the path specified. (Exception from HRESULT: 0x80070003)

Exception Type: System.IO.DirectoryNotFoundException

Stack Trace:
   at Microsoft.Tools.WindowsInstallerXml.Cab.Interop.NativeMethods.CreateCabFinish(IntPtr contextHandle, IntPtr newCabNamesCallBackAddress)
   at Microsoft.Tools.WindowsInstallerXml.Cab.WixCreateCab.Complete(IntPtr newCabNamesCallBackAddress)
   at Microsoft.Tools.WindowsInstallerXml.CabinetBuilder.CreateCabinet(CabinetWorkItem cabinetWorkItem)
   at Microsoft.Tools.WindowsInstallerXml.CabinetBuilder.ProcessWorkItems()
Error[1] (Command): The 'light' application failed with exit code = 1
```

I'm on an up-to-date Windows 10 machine. I tried Command Prompt and Git Bash inside VSCode. My compiler if that helps: 

```
> rustc --version
rustc 1.44.0 (49cae5576 2020-06-01)
```

**Comment by justinmoon** [comment] 2020-07-23 23:38
Seems like this is almost exactly the same as this bug upstream https://github.com/wixtoolset/issues/issues/5809

Should I file an issue over there?

**Comment by volks73** [comment] 2020-07-25 14:11
Thank you for the verbose output from running the commands and trying the example. I tried to reproduce the error on my machine. I am not able to reproduce the error you are seeing, so it might be something specific to your environment or something related to running WiX, cargo, etc. from within VS Code. My environment:

- Rust v1.45.0 (yours is v1.44.0)
- cargo-wix v0.3.0 (compiled and installed using Rust v1.45.0)
-  WiX Toolset v3.11.1 (yours is v3.11.2)

I did the following commands in order:

```dos
C:\>mkdir example
C:\>cd example
C:\>cargo init --bin --vcs none --name example
C:\>dir /B
Cargo.toml
src
wix
C:\>cargo wix
```

I ran these commands under five different prompts: 

1. Alacritty v0.5.0-dev with PowerShell 7.0.3 and admin privileges
2. x64 Native Tools Command Prompt Visual Studio 2019 Command Prompt v16.0 with admin privileges
3. Command Prompt without admin privileges
4. Windows Terminal v1.1.2021.0 with PowerShell 7.0.3 and no admin privileges
5. Git Bash Mintty 3.2.0 without admin privileges.

I encountered no errors from any of WiX's applications (candle.exe and light.exe). Every test yielded a usable MSI. Sorry, but I do not use VS Code so I did not try it. 

The interesting one is Git Bash as that is common between your environment and my environment. This would indicate that it is something specific to your environment; however, I doubt the small version difference between our respective WiX Toolsets is the cause, along with the difference in Rust versions. 

> Seems like this is almost exactly the same as this bug upstream [wixtoolset/issues#5809](https://github.com/wixtoolset/issues/issues/5809)
> 
> Should I file an issue over there?

The existence of an issue with WiX Toolset that has very similar symptoms provides further evidence this is not an issue with cargo-wix. I, admittedly briefly, reviewed the issue. It is closed and there is a merged PR that would suggest a newer version of the WiX Toolset would resolve the issue, but I am not familiar with the WiX Toolset development process and organization, so I am not sure if the PR has actually been released. 

The WiX issue you mention appears to be related to paths and directory names. However, thanks to your output, your paths look fine. There are no spaces or special characters. You are on the C drive instead of another drive (side note, all my tests were on a non-C drive).

I think to definitively say this is a WiX issue, a cargo-wix issue, or an environment issue would be to run the commands that cargo-wix is running but without using cargo-wix and see if the error still occurs. Please try the following from a command prompt (cmd.exe):

```dos
C:\>C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe -dProfile=release -dVersion=0.1.0 -dPlatform=x64 -ext WixUtilExtension -o target\wix\ wix\main.wxs
C:\>C:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe -spdb -ext WixUIExtension -ext WixUtilExtension -cultures:en-US -out target\wix\example-0.1.0-x86_64.msi -b C:\Users\justin\dev\wix\example target\wix\main.wixobj
```

Please make note of trailing slashes as these are important for the light.exe application. If no error, then it is something with your environment or running from VS Code. I would then try again, but from Git Bash to further narrow down the potential source. You will need to escape the paths and adjust the drive letter notation (the following is my guess at the correct format for Git Bash. The verbose output from running in Git Bash will yield the correct formatting with the `[DEBUG] command = ...`  line):

```bash
$ "/c/Program Files (x86)/WiX Toolset v3.11/bin/candle.exe" -dProfile=release -dVersion=0.1.0 -dPlatform=x64 -ext WixUtilExtension -o target/wix/ wix/main.wxs
$ "/c/Program Files (x86)/WiX Toolset v3.11/bin/light.exe" -spdb -ext WixUIExtension -ext WixUtilExtension -cultures:en-US -out target/wix/example-0.1.0-x86_64.msi -b /c/Users/justin/dev/wix/example target/wix/main.wixobj
```

Thanks again for the verbose output. It was very helpful and informative.

**Comment by volks73** [comment] 2020-08-08 14:02
I think this is ultimately caused by something beyond this project. I am going to close this issue, but please feel free to update with new information or details.

**Closed by volks73** 2020-08-08 14:02 UTC
Labels: bug, wontfix

**Comment by justinmoon** [comment] 2020-08-08 17:07
Hey sorry I disappeared. I'll try to check this again when I'm able and report if I discover anything useful.
